In [1]:
!pip install import_ipynb

### 외부 파일을 불러오긴 위한 import_ipynb기능 설치 

In [2]:
import import_ipynb
from m_KNN import classify
from m_KNN import weighted_classify

importing Jupyter notebook from m_KNN.ipynb


### 필자가 작성한 외부 파일 m_KNN에서 classify 함수와 weighted_classify함수를 import해온다 <br>classify 함수와 weighted_classify함수에 대한 주석은 m_KNN inpynb파일에 설명해 두었습니다!!

In [3]:
import numpy as np
#import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris

In [4]:
iris = load_iris()

In [5]:
X = iris.data

In [6]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

X 데이터가 무엇인지 파악한다

In [7]:
y = iris.target

In [8]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [9]:
print(len(y))

150


### y 데이터가 무엇인지 파악한다

In [10]:
y_name = iris.target_names

In [11]:
y_name.shape

(3,)

In [12]:
y_name

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

### y_name 데이터가 무엇인지 파악한다

In [13]:
test_data = []
test_data_int = []
test_label = []
train_data = []
train_label = []

In [14]:
for i in range(0,150):
    if(i % 15 == 14):
        test_data.append(X[i])
        test_label.append(iris.target[i])
    else:
        train_data.append(X[i])
        train_label.append(y[i])

In [15]:
test_data

[array([5.8, 4. , 1.2, 0.2]),
 array([4.7, 3.2, 1.6, 0.2]),
 array([5.1, 3.8, 1.9, 0.4]),
 array([5.2, 2.7, 3.9, 1.4]),
 array([6.4, 2.9, 4.3, 1.3]),
 array([5.5, 2.5, 4. , 1.3]),
 array([6.5, 3. , 5.8, 2.2]),
 array([6. , 2.2, 5. , 1.5]),
 array([6.1, 2.6, 5.6, 1.4]),
 array([5.9, 3. , 5.1, 1.8])]

In [16]:
for i in range (len(test_data)):
    test_data[i] = list(map(float, test_data[i]))

In [17]:
test_data

[[5.8, 4.0, 1.2, 0.2],
 [4.7, 3.2, 1.6, 0.2],
 [5.1, 3.8, 1.9, 0.4],
 [5.2, 2.7, 3.9, 1.4],
 [6.4, 2.9, 4.3, 1.3],
 [5.5, 2.5, 4.0, 1.3],
 [6.5, 3.0, 5.8, 2.2],
 [6.0, 2.2, 5.0, 1.5],
 [6.1, 2.6, 5.6, 1.4],
 [5.9, 3.0, 5.1, 1.8]]

In [18]:
test_label

[0, 0, 0, 1, 1, 1, 2, 2, 2, 2]

In [19]:
train_data

[array([5.1, 3.5, 1.4, 0.2]),
 array([4.9, 3. , 1.4, 0.2]),
 array([4.7, 3.2, 1.3, 0.2]),
 array([4.6, 3.1, 1.5, 0.2]),
 array([5. , 3.6, 1.4, 0.2]),
 array([5.4, 3.9, 1.7, 0.4]),
 array([4.6, 3.4, 1.4, 0.3]),
 array([5. , 3.4, 1.5, 0.2]),
 array([4.4, 2.9, 1.4, 0.2]),
 array([4.9, 3.1, 1.5, 0.1]),
 array([5.4, 3.7, 1.5, 0.2]),
 array([4.8, 3.4, 1.6, 0.2]),
 array([4.8, 3. , 1.4, 0.1]),
 array([4.3, 3. , 1.1, 0.1]),
 array([5.7, 4.4, 1.5, 0.4]),
 array([5.4, 3.9, 1.3, 0.4]),
 array([5.1, 3.5, 1.4, 0.3]),
 array([5.7, 3.8, 1.7, 0.3]),
 array([5.1, 3.8, 1.5, 0.3]),
 array([5.4, 3.4, 1.7, 0.2]),
 array([5.1, 3.7, 1.5, 0.4]),
 array([4.6, 3.6, 1. , 0.2]),
 array([5.1, 3.3, 1.7, 0.5]),
 array([4.8, 3.4, 1.9, 0.2]),
 array([5. , 3. , 1.6, 0.2]),
 array([5. , 3.4, 1.6, 0.4]),
 array([5.2, 3.5, 1.5, 0.2]),
 array([5.2, 3.4, 1.4, 0.2]),
 array([4.8, 3.1, 1.6, 0.2]),
 array([5.4, 3.4, 1.5, 0.4]),
 array([5.2, 4.1, 1.5, 0.1]),
 array([5.5, 4.2, 1.4, 0.2]),
 array([4.9, 3.1, 1.5, 0.2]),
 array([5.

In [20]:
for i in range (len(train_data)):
    train_data[i] = list(map(float, train_data[i]))

In [21]:
train_data

[[5.1, 3.5, 1.4, 0.2],
 [4.9, 3.0, 1.4, 0.2],
 [4.7, 3.2, 1.3, 0.2],
 [4.6, 3.1, 1.5, 0.2],
 [5.0, 3.6, 1.4, 0.2],
 [5.4, 3.9, 1.7, 0.4],
 [4.6, 3.4, 1.4, 0.3],
 [5.0, 3.4, 1.5, 0.2],
 [4.4, 2.9, 1.4, 0.2],
 [4.9, 3.1, 1.5, 0.1],
 [5.4, 3.7, 1.5, 0.2],
 [4.8, 3.4, 1.6, 0.2],
 [4.8, 3.0, 1.4, 0.1],
 [4.3, 3.0, 1.1, 0.1],
 [5.7, 4.4, 1.5, 0.4],
 [5.4, 3.9, 1.3, 0.4],
 [5.1, 3.5, 1.4, 0.3],
 [5.7, 3.8, 1.7, 0.3],
 [5.1, 3.8, 1.5, 0.3],
 [5.4, 3.4, 1.7, 0.2],
 [5.1, 3.7, 1.5, 0.4],
 [4.6, 3.6, 1.0, 0.2],
 [5.1, 3.3, 1.7, 0.5],
 [4.8, 3.4, 1.9, 0.2],
 [5.0, 3.0, 1.6, 0.2],
 [5.0, 3.4, 1.6, 0.4],
 [5.2, 3.5, 1.5, 0.2],
 [5.2, 3.4, 1.4, 0.2],
 [4.8, 3.1, 1.6, 0.2],
 [5.4, 3.4, 1.5, 0.4],
 [5.2, 4.1, 1.5, 0.1],
 [5.5, 4.2, 1.4, 0.2],
 [4.9, 3.1, 1.5, 0.2],
 [5.0, 3.2, 1.2, 0.2],
 [5.5, 3.5, 1.3, 0.2],
 [4.9, 3.6, 1.4, 0.1],
 [4.4, 3.0, 1.3, 0.2],
 [5.1, 3.4, 1.5, 0.2],
 [5.0, 3.5, 1.3, 0.3],
 [4.5, 2.3, 1.3, 0.3],
 [4.4, 3.2, 1.3, 0.2],
 [5.0, 3.5, 1.6, 0.6],
 [4.8, 3.0, 1.4, 0.3],
 [5.1, 3.8,

In [22]:
train_label

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2]

### train test split을 해준다

In [23]:
flowers = {0: 'Setosa', 1: 'Versicolor', 2:'Virginica'}

### Majority Vote, K = 3

In [24]:
for i in range(10):
    print("Test Data Index: "+ str(i), end =' ')
    classify(train_data, test_data[i], 3, train_label)
    print("True class: "+ flowers[int(test_label[i])])# flowers 딕셔너리 안을 참고하면, 0이 나올시 Setosa, 1이 나올시 Versicolor, 2가 나올시 Vitginica가 출력됨을 알 수 있다

Test Data Index: 0 computed class: Setosa True class: Setosa
Test Data Index: 1 computed class: Setosa True class: Setosa
Test Data Index: 2 computed class: Setosa True class: Setosa
Test Data Index: 3 computed class: Versicolor True class: Versicolor
Test Data Index: 4 computed class: Versicolor True class: Versicolor
Test Data Index: 5 computed class: Versicolor True class: Versicolor
Test Data Index: 6 computed class: Virginica True class: Virginica
Test Data Index: 7 computed class: Versicolor True class: Virginica
Test Data Index: 8 computed class: Virginica True class: Virginica
Test Data Index: 9 computed class: Virginica True class: Virginica


### Majority Vote, K = 5

In [25]:
for i in range(10):
    print("Test Data Index: "+ str(i), end =' ')
    classify(train_data, test_data[i], 5, train_label)
    print("True class: "+ flowers[int(test_label[i])])

Test Data Index: 0 computed class: Setosa True class: Setosa
Test Data Index: 1 computed class: Setosa True class: Setosa
Test Data Index: 2 computed class: Setosa True class: Setosa
Test Data Index: 3 computed class: Versicolor True class: Versicolor
Test Data Index: 4 computed class: Versicolor True class: Versicolor
Test Data Index: 5 computed class: Versicolor True class: Versicolor
Test Data Index: 6 computed class: Virginica True class: Virginica
Test Data Index: 7 computed class: Versicolor True class: Virginica
Test Data Index: 8 computed class: Virginica True class: Virginica
Test Data Index: 9 computed class: Virginica True class: Virginica


### Majority Vote, K = 10

In [26]:
for i in range(10):
    print("Test Data Index: "+ str(i), end =' ')
    classify(train_data, test_data[i], 10, train_label)
    print("True class: "+ flowers[int(test_label[i])])

Test Data Index: 0 computed class: Setosa True class: Setosa
Test Data Index: 1 computed class: Setosa True class: Setosa
Test Data Index: 2 computed class: Setosa True class: Setosa
Test Data Index: 3 computed class: Versicolor True class: Versicolor
Test Data Index: 4 computed class: Versicolor True class: Versicolor
Test Data Index: 5 computed class: Versicolor True class: Versicolor
Test Data Index: 6 computed class: Virginica True class: Virginica
Test Data Index: 7 computed class: Virginica True class: Virginica
Test Data Index: 8 computed class: Virginica True class: Virginica
Test Data Index: 9 computed class: Virginica True class: Virginica


### Weighted Majority Vote, K = 3

In [27]:
for i in range(10):
    print("Test Data Index: "+ str(i), end =' ')
    weighted_classify(train_data, test_data[i], 3, train_label)
    print("True class: "+ flowers[int(test_label[i])])

Test Data Index: 0 computed class: Setosa True class: Setosa
Test Data Index: 1 computed class: Setosa True class: Setosa
Test Data Index: 2 computed class: Setosa True class: Setosa
Test Data Index: 3 computed class: Versicolor True class: Versicolor
Test Data Index: 4 computed class: Versicolor True class: Versicolor
Test Data Index: 5 computed class: Versicolor True class: Versicolor
Test Data Index: 6 computed class: Virginica True class: Virginica
Test Data Index: 7 computed class: Versicolor True class: Virginica
Test Data Index: 8 computed class: Versicolor True class: Virginica
Test Data Index: 9 computed class: Virginica True class: Virginica


### Weighted Majority Vote, K = 5

In [28]:
for i in range(10):
    print("Test Data Index: "+ str(i), end =' ')
    weighted_classify(train_data, test_data[i], 5, train_label)
    print("True class: "+ flowers[int(test_label[i])])

Test Data Index: 0 computed class: Setosa True class: Setosa
Test Data Index: 1 computed class: Setosa True class: Setosa
Test Data Index: 2 computed class: Setosa True class: Setosa
Test Data Index: 3 computed class: Versicolor True class: Versicolor
Test Data Index: 4 computed class: Versicolor True class: Versicolor
Test Data Index: 5 computed class: Versicolor True class: Versicolor
Test Data Index: 6 computed class: Virginica True class: Virginica
Test Data Index: 7 computed class: Versicolor True class: Virginica
Test Data Index: 8 computed class: Versicolor True class: Virginica
Test Data Index: 9 computed class: Versicolor True class: Virginica


### Weighted Majority Vote, K = 10

In [29]:
for i in range(10):
    print("Test Data Index: "+ str(i), end =' ')
    weighted_classify(train_data, test_data[i], 10, train_label)
    print("True class: "+ flowers[int(test_label[i])])

Test Data Index: 0 computed class: Setosa True class: Setosa
Test Data Index: 1 computed class: Setosa True class: Setosa
Test Data Index: 2 computed class: Setosa True class: Setosa
Test Data Index: 3 computed class: Versicolor True class: Versicolor
Test Data Index: 4 computed class: Versicolor True class: Versicolor
Test Data Index: 5 computed class: Versicolor True class: Versicolor
Test Data Index: 6 computed class: Virginica True class: Virginica
Test Data Index: 7 computed class: Versicolor True class: Virginica
Test Data Index: 8 computed class: Versicolor True class: Virginica
Test Data Index: 9 computed class: Virginica True class: Virginica


## -------------------------------------과제 끝 ----------------------------------------------------

# !!!번외!!!! -> distance측정을 다르게 하였습니다. 처음에 과제를 시작할때 pandas로 해보았는데, 흥미로워 남겨두었습니다!!

### iris data를 다루기 쉽게 pandas dataframe으로 바꿔준다

In [30]:
import pandas as pd

In [31]:
iris_df = pd.DataFrame(data = iris.data, columns = iris.feature_names)
iris_df['Target'] = iris.target

In [32]:
iris_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   Target  
0       0  
1       0  
2       0  
3       0  
4       0

In [33]:
iris_df.shape

(150, 5)

In [34]:
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     Target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [35]:
iris_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   Target             150 non-null    int32  
dtypes: float64(4), int32(1)
memory usage: 5.4 KB


In [36]:
label = iris_df['Target']
label = pd.DataFrame(label)

In [37]:
label

Target
0         0
1         0
2         0
3         0
4         0
..      ...
145       2
146       2
147       2
148       2
149       2

[150 rows x 1 columns]

In [38]:
iris_df.drop(columns=['Target'], inplace=True)

In [39]:
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

### train과 test를 split 해준다

In [40]:
index = []
for k in range(0,150):
    if (k % 15) == 14:
        continue
    else:
        index.append(k)

In [41]:
data_train = iris_df.iloc[[int(i) for i in index], :]                                         

In [42]:
data_train

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
144                6.7               3.3                5.7               2.5
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3

[140 rows x 4 columns]

In [43]:
data_test = iris_df.iloc[[i for i in range(0,150) if i not in index], :]

In [44]:
data_test

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
14                 5.8               4.0                1.2               0.2
29                 4.7               3.2                1.6               0.2
44                 5.1               3.8                1.9               0.4
59                 5.2               2.7                3.9               1.4
74                 6.4               2.9                4.3               1.3
89                 5.5               2.5                4.0               1.3
104                6.5               3.0                5.8               2.2
119                6.0               2.2                5.0               1.5
134                6.1               2.6                5.6               1.4
149                5.9               3.0                5.1               1.8

In [45]:
label_train = label.iloc[[int(i) for i in index], 0] 

In [46]:
label_train

0      0
1      0
2      0
3      0
4      0
      ..
144    2
145    2
146    2
147    2
148    2
Name: Target, Length: 140, dtype: int32

In [47]:
label_test = label.iloc[[i for i in range(0,150) if i not in index], :]

In [48]:
label_test

Target
14        0
29        0
44        0
59        1
74        1
89        1
104       2
119       2
134       2
149       2

### KNN 알고리즘 구현

In [49]:
flowers = {0: 'Setosa', 1: 'Versicolor', 2:'Virginica'}

In [50]:
def classify(test_data, train_data, labels , k): #test데이터는 1행이 들어올거고, train데이터는 train데이터 전체 
    #inpu는 분류 대상, data는 훈련을 위한 예제의 전체 행렬, labels는 분류 답들(0,1,2), k는 최근접 이웃 수
    #data_set_size = data_set.shape[0]
    diff = test_data - train_data
    diff_sq = diff**2
    row_sum = diff_sq.sum(axis = 1)
    distance = np.sqrt(row_sum)
    sort_dist = distance.argsort()
    #print(sort_dist)
    vote=[]
    for i in range(k):
        vote.append(labels.iloc[int(sort_dist[i])])
    max_flower =  mode(vote)
    print("Computed class: " + str(flowers[max_flower]) + ",", end = '')

In [51]:
def mode(list):
    count = 0
    mode = 0;
    for x in list: 
        if list.count(x) > count:
            count = list.count(x)
            mode = x

    return mode

In [52]:
classify(data_test.iloc[0, :], data_train, label_train, 3)

Computed class: Setosa,

### k 가 3일때

In [53]:
for i in range(10):
    print("Test Data Index: "+ str(i), end=' ')
    classify(data_test.iloc[i, :], data_train, label_train, 3)#마지막 인자는 3 or 5 or 7
    print("True class: "+ flowers[int(label_test.iloc[i])])

Test Data Index: 0 Computed class: Setosa,True class: Setosa
Test Data Index: 1 Computed class: Setosa,True class: Setosa
Test Data Index: 2 Computed class: Setosa,True class: Setosa
Test Data Index: 3 Computed class: Versicolor,True class: Versicolor
Test Data Index: 4 Computed class: Versicolor,True class: Versicolor
Test Data Index: 5 Computed class: Versicolor,True class: Versicolor
Test Data Index: 6 Computed class: Virginica,True class: Virginica
Test Data Index: 7 Computed class: Versicolor,True class: Virginica
Test Data Index: 8 Computed class: Virginica,True class: Virginica
Test Data Index: 9 Computed class: Virginica,True class: Virginica


### k 가 5일때

In [54]:
for i in range(10):
    print("Test Data Index: "+ str(i), end=' ')
    classify(data_test.iloc[i, :], data_train, label_train, 5)#마지막 인자는 3 or 5 or 7
    print("True class: "+ flowers[int(label_test.iloc[i])])

Test Data Index: 0 Computed class: Setosa,True class: Setosa
Test Data Index: 1 Computed class: Setosa,True class: Setosa
Test Data Index: 2 Computed class: Setosa,True class: Setosa
Test Data Index: 3 Computed class: Versicolor,True class: Versicolor
Test Data Index: 4 Computed class: Versicolor,True class: Versicolor
Test Data Index: 5 Computed class: Versicolor,True class: Versicolor
Test Data Index: 6 Computed class: Virginica,True class: Virginica
Test Data Index: 7 Computed class: Versicolor,True class: Virginica
Test Data Index: 8 Computed class: Virginica,True class: Virginica
Test Data Index: 9 Computed class: Virginica,True class: Virginica


### k 가 7일때

In [55]:
for i in range(10):
    print("Test Data Index: "+ str(i), end=' ')
    classify(data_test.iloc[i, :], data_train, label_train, 7)#마지막 인자는 3 or 5 or 7
    print("True class: "+ flowers[int(label_test.iloc[i])])

Test Data Index: 0 Computed class: Setosa,True class: Setosa
Test Data Index: 1 Computed class: Setosa,True class: Setosa
Test Data Index: 2 Computed class: Setosa,True class: Setosa
Test Data Index: 3 Computed class: Versicolor,True class: Versicolor
Test Data Index: 4 Computed class: Versicolor,True class: Versicolor
Test Data Index: 5 Computed class: Versicolor,True class: Versicolor
Test Data Index: 6 Computed class: Virginica,True class: Virginica
Test Data Index: 7 Computed class: Virginica,True class: Virginica
Test Data Index: 8 Computed class: Virginica,True class: Virginica
Test Data Index: 9 Computed class: Virginica,True class: Virginica


### k 가 10일때

In [56]:
for i in range(10):
    print("Test Data Index: "+ str(i), end=' ')
    classify(data_test.iloc[i, :], data_train, label_train, 10)#마지막 인자는 3 or 5 or 7
    print("True class: "+ flowers[int(label_test.iloc[i])])

Test Data Index: 0 Computed class: Setosa,True class: Setosa
Test Data Index: 1 Computed class: Setosa,True class: Setosa
Test Data Index: 2 Computed class: Setosa,True class: Setosa
Test Data Index: 3 Computed class: Versicolor,True class: Versicolor
Test Data Index: 4 Computed class: Versicolor,True class: Versicolor
Test Data Index: 5 Computed class: Versicolor,True class: Versicolor
Test Data Index: 6 Computed class: Virginica,True class: Virginica
Test Data Index: 7 Computed class: Virginica,True class: Virginica
Test Data Index: 8 Computed class: Virginica,True class: Virginica
Test Data Index: 9 Computed class: Virginica,True class: Virginica
